### ISSUE TITLE
make WITH_WEBSOCKETS=yes,  error~

### ISSUE THREAD

**Issue by xinchu** [eclipse/mosquitto#902]
the version:
mosquitto 1.5
libwebsockets 3.0.0
os    centos 7

Sudo make WITH_WEBSOCKETS=yes
Set -e; for d in lib client src; do make -C ${d}; done
Make[1]: Go to the directory "/usr/local/src/mosquitto-1.5/lib"
Make -C cpp
Make[2]: Go to the directory "/usr/local/src/mosquitto-1.5/lib/cpp"
Make[2]: No need to do anything with "all".
Make[2]: Leave the directory "/usr/local/src/mosquitto-1.5/lib/cpp"
Make[1]: Leave the directory "/usr/local/src/mosquitto-1.5/lib"
Make[1]: Go to the directory "/usr/local/src/mosquitto-1.5/client"
Make[1]: No need to do anything with "all".
Make[1]: Leave the directory "/usr/local/src/mosquitto-1.5/client"
Make[1]: Go to the directory "/usr/local/src/mosquitto-1.5/src"
Cc -Wall -ggdb -O2 -I. -I.. -I../lib -DVERSION="\"1.5\"" -DWITH_BROKER -DWITH_TLS -DWITH_TLS_PSK -DWITH_UUID -DWITH_BRIDGE -DWITH_PERSISTENCE -DWITH_MEMORY_TRACKING -DWITH_SYS_TREE -DWITH_WEBSOCKETS -DWITH_EC -DWITH_EPOLL -c websockets.c -o websockets.o
Websockets.c: In the function ‘http__canonical_filename’:
Websockets.c:446:2: Warning: implicitly declare the function ‘realpath’ [-Wimplicit-function-declaration]
  Filename_canonical = realpath(filename, NULL);
  ^
Websockets.c:446:21: Warning: Assign an integer to a pointer when assigning, no type conversion [default enabled]
  Filename_canonical = realpath(filename, NULL);
                     ^
Websockets.c: In the function 'callback_http':
Websockets.c:542:27: Error: ‘S_IFDIR’ is not declared (first used in this function)
    If((filestat.st_mode & S_IFDIR) == S_IFDIR){
                           ^
Websockets.c:542:27: Note: Each undeclared identifier is only reported once in the function in which it appears
Websockets.c:554:27: Error: ‘S_IFREG’ is not declared (first used in this function)
    If((filestat.st_mode & S_IFREG) != S_IFREG){
                           ^
Websockets.c: In the function ‘mosq_websockets_init’:
Websockets.c:705:18: Warning: Assign an integer to a pointer when assigning, no type conversion [default enabled]
   User->http_dir = realpath(listener->http_dir, NULL);
                  ^
Make[1]: *** [websockets.o] error 1
Make[1]: Leave the directory "/usr/local/src/mosquitto-1.5/src"
Make: *** [mosquitto] error 2

**Comment by karlp** [comment]
What OS host?

**Comment by xinchu** [comment]
centos 7 ~

**Comment by toast-uz** [comment]
I confirmed this issue on Cent7, while no problem with mosquitto v1.4.15. It was regardless with the version of libwebsockets (I checked v2.3, v2.4, v3.0).

**Comment by Tifaifai** [comment]
looks like this problem : https://github.com/eclipse/mosquitto/pull/791#issuecomment-383753375
you have need  this line : # define _DEFAULT_SOURCE 1

**Comment by toast-uz** [comment]
Thanks @Tifaifai , looks like #791 but cannot use the same remedy already merged?

**Comment by Tifaifai** [comment]
Have you tested this PR : https://github.com/eclipse/mosquitto/pull/862

48 PR in waiting ... ;) maybe bugs already fixed ;)

**Comment by toast-uz** [comment]
Thanks. Compiled with #862 .

I'm long waiting for fiexes and develop branch on v1.5 to open. :)

**Comment by xinchu** [comment]
@karlp @toast-uz @Tifaifai Thank you for your reply. I will work with the v1.4.15 version first. By the way, is there a time or version of the plan to fix this?

**Comment by toast-uz** [comment]
Thanks @xinchu , keep this issue until #862 merged.
Sorry I'm not sure when. I have several PRs wait to be merged for a year. :)

**Comment by ralight** [comment]
Could you please test the `fixes` branch? It has some fixes for building on other platforms that I believe fix this problem.

**Comment by toast-uz** [comment]
I could on Cent7 by the latest fixes branch. @xinchu , try it.
