### PR TITLE
[280] Fix build with libressl

### LINKED ISSUE #280: Build failure with libressl
It seems that commit fff741613eb9dbf462ba7eafe9d9f15f80a9c623 broke builds with libressl:

```
...
gcc -Os -fomit-frame-pointer -Os -fomit-frame-pointer -I. -I.. -I../lib -Os -fomit-frame-pointer -DVERSION="\"1.4.10\"" -DTIMESTAMP="\"2016-10-04 10:29:22+0000\"" -DWITH_BROKER -DWITH_TLS -DWITH_UUID -DWITH_BRIDGE -DWITH_PERSISTENCE -DWITH_SYS_TREE -DWITH_WEBSOCKETS -DWITH_EC -c ../lib/will_mosq.c -o will_mosq.o
security_default.c: In function '_pw_digest':
security_default.c:798:12: warning: implicit declaration of function 'EVP_MD_CTX_new' [-Wimplicit-function-declaration]
  context = EVP_MD_CTX_new();
            ^~~~~~~~~~~~~~
security_default.c:798:10: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  context = EVP_MD_CTX_new();
          ^
security_default.c:804:2: warning: implicit declaration of function 'EVP_MD_CTX_free' [-Wimplicit-function-declaration]
  EVP_MD_CTX_free(context);
  ^~~~~~~~~~~~~~~
gcc -Os -fomit-frame-pointer -Os -fomit-frame-pointer -c mosquitto_passwd.c -o mosquitto_passwd.o
mosquitto_passwd.c: In function 'output_new_password':
mosquitto_passwd.c:128:12: warning: implicit declaration of function 'EVP_MD_CTX_new' [-Wimplicit-function-declaration]
  context = EVP_MD_CTX_new();
            ^~~~~~~~~~~~~~
mosquitto_passwd.c:128:10: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  context = EVP_MD_CTX_new();
          ^
mosquitto_passwd.c:133:2: warning: implicit declaration of function 'EVP_MD_CTX_free' [-Wimplicit-function-declaration]
  EVP_MD_CTX_free(context);
  ^~~~~~~~~~~~~~~
gcc mosquitto_passwd.o -o mosquitto_passwd -Wl,--as-needed -lcrypto
mosquitto_passwd.o: In function `output_new_password':
mosquitto_passwd.c:(.text+0x36a): undefined reference to `EVP_MD_CTX_new'
mosquitto_passwd.c:(.text+0x3c6): undefined reference to `EVP_MD_CTX_free'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:99: mosquitto_passwd] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/ncopa/aports/main/mosquitto/src/mosquitto-1.4.10/src'
make: *** [Makefile:21: mosquitto] Error 2
```

### PR DESCRIPTION
**Pull request by ncopa**
Closes #280

Fix building with libressl which broke in commit fff741613 (Support for
openssl 1.1.0).

Bug: #280

Signed-off-by: Natanael Copa ncopa@alpinelinux.org

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=280

**Comment by ralight** [comment]
The joy of forks :)

If you sign the Eclipse ECA I'll merge this request, thanks for spotting it.

**Comment by ril3y** [comment]
Sigh.... Is this still really an issue?  I am getting the same error today.  Or am I missing something?

**Comment by ralight** [comment]
This has been fixed separately, so I am closing this PR.
