### ISSUE TITLE
undefined reference to `libwebsockets_return_http_status'

### ISSUE THREAD

**Issue by FernandoGarcia** [eclipse/mosquitto#371]
Hi!

I would like to know to fix this compiling error:

```
/root/mosquitto/src/websockets.c:474: undefined reference to `libwebsockets_return_http_status'
/root/mosquitto/src/websockets.c:433: undefined reference to `libwebsockets_return_http_status'
/root/mosquitto/src/websockets.c:496: undefined reference to `libwebsockets_return_http_status'
collect2: error: ld returned 1 exit status
make[1]: *** [mosquitto] Error 1
make[1]: Leaving directory `/root/mosquitto/src'
make: *** [mosquitto] Error 2
```
I have fixed the typo [pointed here](https://github.com/eclipse/mosquitto/commit/03d4b8c27029da25dd350df3ca86dd7a6f1393fe) before and now I have this error.

Can someone help me please?

Best regards.

**Comment by FernandoGarcia** [comment]
I have installed the libwebsockets using this commands:

`sudo apt-get install libwebsockets-dev`

and 

```
git clone https://github.com/warmcat/libwebsockets.git
cd libwebsockets
mkdir build  
cd build  
cmake ..  
make  
sudo make install 
```

`pkg-config --modversion libwebsockets`

Returns 2.1.0.

**Comment by FernandoGarcia** [comment]
Well, after install this libraries I others errors:

`sudo apt-get install uuid-dev xsltproc docbook-xsl`

```
mosquitto.o: In function `main':
/root/mosquitto/src/mosquitto.c:399: undefined reference to `lws_context_destroy                                          '
loop.o: In function `do_disconnect':
/root/mosquitto/src/loop.c:404: undefined reference to `lws_callback_on_writable                                          '
loop.o: In function `mosquitto_main_loop':
/root/mosquitto/src/loop.c:378: undefined reference to `lws_service'
net_mosq.o: In function `_mosquitto_socket_close':
/root/mosquitto/src/../lib/net_mosq.c:235: undefined reference to `lws_callback_                                          on_writable'
net_mosq.o: In function `_mosquitto_packet_queue':
/root/mosquitto/src/../lib/net_mosq.c:169: undefined reference to `lws_callback_                                          on_writable'
websockets.o: In function `callback_http':
/root/mosquitto/src/websockets.c:416: undefined reference to `lws_get_context'
/root/mosquitto/src/websockets.c:416: undefined reference to `lws_context_user'
/root/mosquitto/src/websockets.c:513: undefined reference to `lws_write'
/root/mosquitto/src/websockets.c:517: undefined reference to `lws_callback_on_wr                                          itable'
/root/mosquitto/src/websockets.c:542: undefined reference to `lws_write'
/root/mosquitto/src/websockets.c:483: undefined reference to `lws_return_http_st                                          atus'
/root/mosquitto/src/websockets.c:474: undefined reference to `lws_return_http_st                                          atus'
/root/mosquitto/src/websockets.c:433: undefined reference to `lws_return_http_st                                          atus'
/root/mosquitto/src/websockets.c:496: undefined reference to `lws_return_http_st                                          atus'
/root/mosquitto/src/websockets.c:445: undefined reference to `lws_return_http_st                                          atus'
websockets.o:/root/mosquitto/src/websockets.c:472: more undefined references to                                           `lws_return_http_status' follow
websockets.o: In function `callback_mqtt':
/root/mosquitto/src/websockets.c:257: undefined reference to `lws_write'
/root/mosquitto/src/websockets.c:185: undefined reference to `lws_get_protocol'
/root/mosquitto/src/websockets.c:205: undefined reference to `lws_get_socket_fd'
/root/mosquitto/src/websockets.c:290: undefined reference to `lws_callback_on_wr                                          itable'
/root/mosquitto/src/websockets.c:286: undefined reference to `lws_callback_on_wr                                          itable'
websockets.o: In function `mosq_websockets_init':
/root/mosquitto/src/websockets.c:650: undefined reference to `lws_create_context                                          '
collect2: error: ld returned 1 exit status
make[1]: *** [mosquitto] Error 1
make[1]: Leaving directory `/root/mosquitto/src'
make: *** [mosquitto] Error 2
```

**Comment by absalom-muc** [comment]
I've just build v1.4.10 from https://mosquitto.org/download/ and made the 2 fixes you mentioned.  It was necessary to 
`sudo apt remove libwebsockets3`
before. Then the compiler used the right libwebsockets 2.1.0
Addtionally I recommend that you try it with a more simple configuration. Therefore you could make the following changes in config.mk:
```
WITH_SRV:=no
WITH_UUID:=no
WITH_WEBSOCKETS:=yes
WITH_DOCS:=no
```
I believe with `sudo apt-get install uuid-dev xsltproc docbook-xsl` you could install packages which are not up to date and maybe not compatible with mosquitto.

**Comment by FernandoGarcia** [comment]
Thank you very much!

Was compiled after remove libwebsockets3 as you told.

I had to reinstall Mosquitto because the version 1.4.10 doesn't work with websockets, I did it work with 1.4.8 as suggested here: https://github.com/eclipse/mosquitto/issues/336
:)
Best regards.

**Comment by nikhilve99** [comment]
hi guys,

i am trying to upgrade mosquitto 1.4.10 to 1.4.14 and getting below error:

make[2]: Entering directory `/root/mosquitto/lib/cpp'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/root/mosquitto/lib/cpp'
make[1]: Leaving directory `/root/mosquitto/lib'
make[1]: Entering directory `/root/mosquitto/client'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/root/mosquitto/client'
make[1]: Entering directory `/root/mosquitto/src'
cc mosquitto.o bridge.o conf.o context.o database.o logging.o loop.o memory_mosq.o persist.o net.o net_mosq.o read_handle.o read_handle_client.o read_handle_server.o read_handle_shared.o security.o security_default.o send_client_mosq.o send_mosq.o send_server.o service.o subs.o sys_tree.o time_mosq.o tls_mosq.o util_mosq.o websockets.o will_mosq.o -o mosquitto  -ldl -lm -lrt -Wl,--dynamic-list=linker.syms -lssl -lcrypto -luuid -lwebsockets
mosquitto.o: In function `main':
/root/mosquitto/src/mosquitto.c:352: undefined reference to `mosq_websockets_init'
collect2: error: ld returned 1 exit status
make[1]: *** [mosquitto] Error 1
make[1]: Leaving directory `/root/mosquitto/src'
make: *** [mosquitto] Error 2



kindly help to resolve this.

Regards
Nikhil
