### ISSUE TITLE
websockets on Freebsd 13.1 connects then immediately disconnects

### ISSUE THREAD

**Issue by rodneygmorgan** [eclipse/mosquitto#2755]
Mosquitto built from ports after tweaks to the libwebsockets port (added  LWS_WITH_EXTERNAL_POLL LWS_CALLBACK_ADD_POLL_FD) to Makefile.  Both ports build without errors.  Issue confirmed with several clients.  Once the client connects it immediately disconnects.  It appears to happen in websockets.c in the callback_mqtt() function case statement for LWS_CALLBACK_CLOSED.  I added a log_printf statement make this assumption.  Here is the log file output:

1676606750: New client connected from 10.0.0.193:53052 as mqttjs_a375c484 (p2, c1, k60).
1676606750: Client gonna be disconnected because 'LWS_CALLBACK_CLOSED'.
1676606750: Client mqttjs_a375c484 closed its connection.

mosquitto works perfectly with MQTT protocol.  I suspect this is caused by the libwebsockets port (which has no maintainer).

Any help/suggestion to diagnose the root cause is welcome.

**Comment by ralight** [comment]
Would you care to try out the `develop` branch? That removes the need for libwebsockets, which simplifies things greatly and improves websockets performance as well. It would be good to have some feedback on it from the freebsd perspective.

**Comment by rodneygmorgan** [comment]
Roger, I'll give it a try this week.

**Comment by h31p** [comment]
> Would you care to try out the `develop` branch? That removes the need for libwebsockets, which simplifies things greatly and improves websockets performance as well. It would be good to have some feedback on it from the freebsd perspective.

develop branch doesn't compile on the latest FreeBSD-13.2 :
`[  4%] Building C object lib/CMakeFiles/libmosquitto.dir/options.c.o
/usr/local/src/mosquitto/mosquitto/lib/options.c:353:8: error: use of undeclared identifier 'MOSQ_OPT_HTTP_PATH'
                case MOSQ_OPT_HTTP_PATH:
                     ^
/usr/local/src/mosquitto/mosquitto/lib/options.c:439:8: error: use of undeclared identifier 'MOSQ_OPT_DISABLE_SOCKETPAIR'
                case MOSQ_OPT_DISABLE_SOCKETPAIR:
                     ^
/usr/local/src/mosquitto/mosquitto/lib/options.c:513:8: error: use of undeclared identifier 'MOSQ_OPT_TRANSPORT'
                case MOSQ_OPT_TRANSPORT:
                     ^
/usr/local/src/mosquitto/mosquitto/lib/options.c:525:8: error: use of undeclared identifier 'MOSQ_OPT_HTTP_HEADER_SIZE'
                case MOSQ_OPT_HTTP_HEADER_SIZE:
                     ^
4 errors generated.
*** Error code 1

Stop.
`

**Comment by rodneygmorgan** [comment]
Roger,

Finally back with time to work on this.  Where can I download the
development branch.  Specifically for FreeBSD since the websockets library
doesn't work on FreeBSD.

Rod

**Comment by diizzyy** [comment]
@rodneygmorgan 
https://github.com/eclipse/mosquitto/tree/develop is what you're looking for

**Comment by diizzyy** [comment]
Seems like it's fixed in dev branch
https://forums.freebsd.org/threads/mosquitto-and-websockets-disconnect-after-initial-packets.89633/#post-634112
