### ISSUE TITLE
build fails if OPENSSL_NO_ENGINE is defined

### ISSUE THREAD

**Issue by bmork** [eclipse/mosquitto#2432]
net__load_engine() is called if WITH_TLS is defined but not built if OPENSSL_NO_ENGINE is defined.  Causing this error:

```
ccache_cc  -I. -I.. -I../include -I../../include -I../lib -DWITH_TLS -DWITH_TLS_PSK -DWITH_BRIDGE -DWITH_PERSISTENCE -DWITH_MEMORY_TRACKING -DWITH_SYS_TREE -DWITH_EC -DWITH_CONTROL -DWITH_UNIX_SOCKETS -DWITH_EPOLL -I../deps -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -ffile-prefix-map=/usr/local/src/openwrt/build_dir/target-mips_24kc_musl/mosquitto-ssl/mosquitto-2.0.13=mosquitto-2.0.13 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/usr/local/src/openwrt/staging_dir/toolchain-mips_24kc_gcc-11.2.0_musl/usr/include -I/usr/local/src/openwrt/staging_dir/toolchain-mips_24kc_gcc-11.2.0_musl/include/fortify -I/usr/local/src/openwrt/staging_dir/toolchain-mips_24kc_gcc-11.2.0_musl/include  -DVERSION="\"2.0.13\"" -DWITH_BROKER -c net.c -o net.o
net.c: In function 'net__tls_load_verify':
net.c:608:12: warning: implicit declaration of function 'net__load_engine'; did you mean 'net__load_crl_file'? [-Wimplicit-function-declaration]
  608 |         if(net__load_engine(listener)){
      |            ^~~~~~~~~~~~~~~~
      |            net__load_crl_file
```

Introduced by commit 376226c129aafddcb0fc5592cab73e3b009204a1  
This part is buggy:

```
@@ -499,14 +499,16 @@ int net__load_certificates(struct mosquitto__listener *listener)
			return rc;
		}
	}
#else
	UNUSED(listener);
#endif
	return MOSQ_ERR_SUCCESS;
}


#if defined(WITH_TLS) && !defined(OPENSSL_NO_ENGINE)
static int net__load_engine(struct mosquitto__listener *listener)
{
#if defined(WITH_TLS) && !defined(OPENSSL_NO_ENGINE)
	ENGINE *engine = NULL;
	UI_METHOD *ui_method;
	EVP_PKEY *pkey;
@@ -556,10 +558,10 @@ static int net__load_engine(struct mosquitto__listener *listener)
		}
	}
	ENGINE_free(engine); /* release the structural reference from ENGINE_by_id() */
#endif

	return MOSQ_ERR_SUCCESS;
}
#endif


int net__tls_load_verify(struct mosquitto__listener *listener)
```

**Comment by peter-winter** [comment]
Confirmed, I have the same issue.

**Comment by ralight** [comment]
Thank you, this was fixed in the commit linked to #2589.
