### ISSUE TITLE
Cannot build on macos 10.15

### ISSUE THREAD

**Issue by LeSuisse** [eclipse/mosquitto#2277]
The build logs show the following errors:
```
[ 91%] Linking C shared module mosquitto_dynamic_security.so
Undefined symbols for architecture x86_64:
  "_BIO_ctrl", referenced from:
      _dynsec_auth__base64_encode in auth.c.o
      _dynsec_auth__base64_decode in auth.c.o
  "_BIO_f_base64", referenced from:
      _dynsec_auth__base64_encode in auth.c.o
      _dynsec_auth__base64_decode in auth.c.o
  "_BIO_free_all", referenced from:
      _dynsec_auth__base64_encode in auth.c.o
      _dynsec_auth__base64_decode in auth.c.o
  "_BIO_new", referenced from:
      _dynsec_auth__base64_encode in auth.c.o
      _dynsec_auth__base64_decode in auth.c.o
  "_BIO_push", referenced from:
      _dynsec_auth__base64_encode in auth.c.o
      _dynsec_auth__base64_decode in auth.c.o
  "_BIO_read", referenced from:
      _dynsec_auth__base64_decode in auth.c.o
  "_BIO_s_mem", referenced from:
      _dynsec_auth__base64_encode in auth.c.o
      _dynsec_auth__base64_decode in auth.c.o
  "_BIO_set_flags", referenced from:
      _dynsec_auth__base64_encode in auth.c.o
      _dynsec_auth__base64_decode in auth.c.o
  "_BIO_write", referenced from:
      _dynsec_auth__base64_encode in auth.c.o
      _dynsec_auth__base64_decode in auth.c.o
  "_EVP_get_digestbyname", referenced from:
      _dynsec_auth__pw_hash in auth.c.o
      _dynsec_auth__basic_auth_callback in auth.c.o
  "_PKCS5_PBKDF2_HMAC", referenced from:
      _dynsec_auth__pw_hash in auth.c.o
      _dynsec_auth__basic_auth_callback in auth.c.o
  "_RAND_bytes", referenced from:
      _dynsec_auth__pw_hash in auth.c.o
  "_mosquitto_broker_publish", referenced from:
      _dynsec_control_callback in plugin.c.o
  "_mosquitto_callback_register", referenced from:
      _mosquitto_plugin_init in plugin.c.o
  "_mosquitto_callback_unregister", referenced from:
      _mosquitto_plugin_cleanup in plugin.c.o
  "_mosquitto_calloc", referenced from:
      _dynsec_auth__base64_decode in auth.c.o
      _dynsec_clients__config_load in clients.c.o
      _dynsec_clients__process_create in clients.c.o
      _dynsec_groups__config_load in groups.c.o
      _dynsec_groups__process_create in groups.c.o
      _mosquitto_plugin_init in plugin.c.o
      _dynsec_roles__config_load in roles.c.o

<snip>

ld: symbol(s) not found for architecture x86_64
```

The issue seems to have been introduced by e21eaeca37196439b3e89bb8fd2eb1903ef94845

Issue initially spotted here: https://github.com/NixOS/nixpkgs/pull/132700#issuecomment-892993331

**Comment by ralight** [comment]
Thanks very

**Comment by LeSuisse** [comment]
Issue seems to still exist in the 2.0.12, see https://github.com/NixOS/nixpkgs/pull/136377#issuecomment-910655518
Should this be re-opened?
